# Generated by Django 3.0.3 on 2024-12-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestMortalityRate',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=256)),
                ('country_code', models.CharField(max_length=256)),
                ('year_2015', models.FloatField()),
                ('year_2016', models.FloatField()),
                ('year_2017', models.FloatField()),
                ('year_2018', models.FloatField()),
                ('year_2019', models.FloatField()),
            ],
        ),
    ]
