# Generated by Django 3.0.3 on 2024-12-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortometricsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=256)),
                ('country_code', models.CharField(max_length=256)),
            ],
        ),
    ]
