# Generated by Django 3.0.3 on 2024-12-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortometricsapp', '0002_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatestMortalityRate',
        ),
    ]
