# Generated by Django 3.0.3 on 2024-12-13 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortometricsapp', '0005_auto_20231213_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortalityrate',
            name='country_data',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='mortometricsapp.Country'),
        ),
        migrations.CreateModel(
            name='MaleMortalityRate',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('year_2000', models.FloatField()),
                ('year_2001', models.FloatField()),
                ('year_2002', models.FloatField()),
                ('year_2003', models.FloatField()),
                ('year_2004', models.FloatField()),
                ('year_2005', models.FloatField()),
                ('year_2006', models.FloatField()),
                ('year_2007', models.FloatField()),
                ('year_2008', models.FloatField()),
                ('year_2009', models.FloatField()),
                ('year_2010', models.FloatField()),
                ('year_2011', models.FloatField()),
                ('year_2012', models.FloatField()),
                ('year_2013', models.FloatField()),
                ('year_2014', models.FloatField()),
                ('year_2015', models.FloatField()),
                ('year_2016', models.FloatField()),
                ('year_2017', models.FloatField()),
                ('year_2018', models.FloatField()),
                ('year_2019', models.FloatField()),
                ('country_data', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='mortometricsapp.Country')),
            ],
        ),
        migrations.CreateModel(
            name='FemaleMortalityRate',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('year_2000', models.FloatField()),
                ('year_2001', models.FloatField()),
                ('year_2002', models.FloatField()),
                ('year_2003', models.FloatField()),
                ('year_2004', models.FloatField()),
                ('year_2005', models.FloatField()),
                ('year_2006', models.FloatField()),
                ('year_2007', models.FloatField()),
                ('year_2008', models.FloatField()),
                ('year_2009', models.FloatField()),
                ('year_2010', models.FloatField()),
                ('year_2011', models.FloatField()),
                ('year_2012', models.FloatField()),
                ('year_2013', models.FloatField()),
                ('year_2014', models.FloatField()),
                ('year_2015', models.FloatField()),
                ('year_2016', models.FloatField()),
                ('year_2017', models.FloatField()),
                ('year_2018', models.FloatField()),
                ('year_2019', models.FloatField()),
                ('country_data', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='mortometricsapp.Country')),
            ],
        ),
    ]
