# Generated by Django 3.0.3 on 2024-12-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortometricsapp', '0006_auto_20231213_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortalityrate',
            name='country_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
