# Generated by Django 3.0.3 on 2024-12-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortometricsapp', '0007_mortalityrate_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='femalemortalityrate',
            name='country_data',
        ),
        migrations.RemoveField(
            model_name='malemortalityrate',
            name='country_data',
        ),
        migrations.RemoveField(
            model_name='mortalityrate',
            name='country_data',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='FemaleMortalityRate',
        ),
        migrations.DeleteModel(
            name='MaleMortalityRate',
        ),
        migrations.DeleteModel(
            name='MortalityRate',
        ),
    ]
