# Generated by Django 3.0.3 on 2024-12-15 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mortometricsapp', '0008_auto_20231215_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=256)),
                ('country_code', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MortalityRate',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(default='', max_length=256)),
                ('year_2000', models.FloatField()),
                ('year_2001', models.FloatField()),
                ('year_2002', models.FloatField()),
                ('year_2003', models.FloatField()),
                ('year_2004', models.FloatField()),
                ('year_2005', models.FloatField()),
                ('year_2006', models.FloatField()),
                ('year_2007', models.FloatField()),
                ('year_2008', models.FloatField()),
                ('year_2009', models.FloatField()),
                ('year_2010', models.FloatField()),
                ('year_2011', models.FloatField()),
                ('year_2012', models.FloatField()),
                ('year_2013', models.FloatField()),
                ('year_2014', models.FloatField()),
                ('year_2015', models.FloatField()),
                ('year_2016', models.FloatField()),
                ('year_2017', models.FloatField()),
                ('year_2018', models.FloatField()),
                ('year_2019', models.FloatField()),
                ('country_data', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='mortometricsapp.Country')),
            ],
        ),
        migrations.CreateModel(
            name='MaleMortalityRate',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(default='', max_length=256)),
                ('year_2000', models.FloatField()),
                ('year_2001', models.FloatField()),
                ('year_2002', models.FloatField()),
                ('year_2003', models.FloatField()),
                ('year_2004', models.FloatField()),
                ('year_2005', models.FloatField()),
                ('year_2006', models.FloatField()),
                ('year_2007', models.FloatField()),
                ('year_2008', models.FloatField()),
                ('year_2009', models.FloatField()),
                ('year_2010', models.FloatField()),
                ('year_2011', models.FloatField()),
                ('year_2012', models.FloatField()),
                ('year_2013', models.FloatField()),
                ('year_2014', models.FloatField()),
                ('year_2015', models.FloatField()),
                ('year_2016', models.FloatField()),
                ('year_2017', models.FloatField()),
                ('year_2018', models.FloatField()),
                ('year_2019', models.FloatField()),
                ('country_data', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='mortometricsapp.Country')),
            ],
        ),
        migrations.CreateModel(
            name='FemaleMortalityRate',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(default='', max_length=256)),
                ('year_2000', models.FloatField()),
                ('year_2001', models.FloatField()),
                ('year_2002', models.FloatField()),
                ('year_2003', models.FloatField()),
                ('year_2004', models.FloatField()),
                ('year_2005', models.FloatField()),
                ('year_2006', models.FloatField()),
                ('year_2007', models.FloatField()),
                ('year_2008', models.FloatField()),
                ('year_2009', models.FloatField()),
                ('year_2010', models.FloatField()),
                ('year_2011', models.FloatField()),
                ('year_2012', models.FloatField()),
                ('year_2013', models.FloatField()),
                ('year_2014', models.FloatField()),
                ('year_2015', models.FloatField()),
                ('year_2016', models.FloatField()),
                ('year_2017', models.FloatField()),
                ('year_2018', models.FloatField()),
                ('year_2019', models.FloatField()),
                ('country_data', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='mortometricsapp.Country')),
            ],
        ),
    ]
