# Generated by Django 3.0.3 on 2024-12-16 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortometricsapp',
         '0009_country_femalemortalityrate_malemortalityrate_mortalityrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryOfCountry',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest_mortality_year', models.IntegerField()),
                ('highest_mortality_year', models.IntegerField()),
                ('avg_overall_mortality_rate', models.FloatField()),
                ('avg_male_mortality_rate', models.FloatField()),
                ('avg_female_mortality_rate', models.FloatField()),
                ('country', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='mortometricsapp.Country')),
            ],
        ),
    ]
