# Generated by Django 3.0.3 on 2024-12-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortometricsapp', '0010_summaryofcountry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='femalemortalityrate',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='malemortalityrate',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='mortalityrate',
            name='country_name',
        ),
    ]
