# Generated by Django 3.0.3 on 2024-12-19 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortometricsapp', '0011_auto_20231217_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(
                max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='femalemortalityrate',
            name='country_data',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='mortometricsapp.Country', unique=True),
        ),
        migrations.AlterField(
            model_name='malemortalityrate',
            name='country_data',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='mortometricsapp.Country', unique=True),
        ),
        migrations.AlterField(
            model_name='mortalityrate',
            name='country_data',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='mortometricsapp.Country', unique=True),
        ),
        migrations.AlterField(
            model_name='summaryofcountry',
            name='country',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='mortometricsapp.Country', unique=True),
        ),
    ]
