# Generated by Django 3.0.3 on 2024-12-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortometricsapp', '0012_auto_20231219_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortalityrate',
            name='country_data',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='mortometricsapp.Country'),
        ),
    ]
