# Generated by Django 3.0.3 on 2024-12-19 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortometricsapp', '0013_auto_20231219_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femalemortalityrate',
            name='country_data',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='mortometricsapp.Country'),
        ),
        migrations.AlterField(
            model_name='malemortalityrate',
            name='country_data',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='mortometricsapp.Country'),
        ),
        migrations.AlterField(
            model_name='summaryofcountry',
            name='country',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='mortometricsapp.Country'),
        ),
    ]
